name: sorgummi_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  args: ^2.4.2  # ✅ TAMBAHAN
  image_picker: ^1.2.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sorghum_bg.png     # Gambar background Screen 1
    - assets/images/logo.png           # Gambar logo tanaman (di Screen 1)
    - assets/images/farmer.png         # Gambar ilustrasi petani (di Screen 2)
    - assets/images/banner_bg.png      # Gambar banner kebun sorgum (di Screen 3)
    - assets/images/leaf.png 
    - assets/images/persiapan_lahan.png
    - assets/images/daun_kuning.png
    - assets/images/pemupukan.png